### PR TITLE
Feature: Add --start_from option to CLI

### PR DESCRIPTION
**Pull request by daviddemeij**
When running s2p it can be convenient to be able to restart the pipeline from a specific step, either to try some different parameters while not having to rerun the entire pipeline or to continue processing after an interruption or error.

I added numbering to the steps so that it is easy to understand what step to use as an input.

### CODE REVIEW

**Comment by carlodef** [comment]
Thank you @daviddemeij! 

For some reason the CI tests aren't triggered anymore on pull requests, I'll have a look to fix that in order to get the tests run before we merge.

**Comment by daviddemeij** [comment]
There have been some issues with Github today, maybe that is why it didn't run the CI test?

**Comment by daviddemeij** [comment]
@carlodef Apparently I had to enable CI workflows in my forked repository (disabled by default). So the CI [runs in my repository](https://github.com/daviddemeij/s2p/actions/runs/2014904395) now, but it still doesn't show up here. This might have something to do with a security upgrade Github implemented. You might need to approve running the CI somewhere:
https://github.blog/2021-04-22-github-actions-update-helping-maintainers-combat-bad-actors/

Or maybe you should add running the CI on `pull_request`. So changing 
```
on: [push]
```
to 
```
on: [push, pull_request]
```
in `build.yml` and` tests.yml`.

**Comment by carlodef** [comment]
Hi @daviddemeij, thanks for your suggestions on how to fix the CI config. I edited the github actions yml config files and added status checks in the branch protection rules, and the CI ran as expected.

**Review by carlodef — APPROVED** [review]
Looks good to me!

**Pull request merged**
